
FROM debian:jessie

RUN apt-get update
RUN apt-get -y install git g++ cmake pkg-config flex bison

RUN cd /root && git clone --depth 1 https://github.com/rizinorg/rizin && cd rizin && ./configure && make -j4 && make install

CMD []

