
FROM archlinux:latest

RUN pacman --noconfirm -Syu
RUN pacman --noconfirm -S git gcc make cmake pkg-config flex bison meson ninja

RUN cd /root && \
	git clone --recurse-submodules --depth 1 https://github.com/rizinorg/rizin && \
	cd rizin && \
	meson build --prefix=/usr && \
	ninja -C build && \
	ninja -C build install

CMD []

