name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.7.x]   
        # Prevent one job from pausing the rest
        fail-fast: [false]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        persist-credentials: false
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: bison flex
    - name: py dependencies
      run: |
        pip install meson ninja
    - name: repo dependencies
      shell: bash
      run: |
        git clone --depth 1 https://github.com/radareorg/radare2
        git clone --depth 1 https://github.com/radareorg/cutter
    - name: set env
      run: |
        echo '::set-env name=INSTALL_PREFIX::${{ github.workspace }}/radare2-prefix'
        echo '::set-env name=CUTTER_PATH::${{ github.workspace }}/cutter'
    - name: Radare2 build
      shell: cmd
      run: |
        cd radare2 
        mkdir build
        cd build
        meson --prefix="%INSTALL_PREFIX%" ..
        ninja
        ninja install
        cd ../..
    - name: msys dependencies
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -Sy --noconfirm bison flex"
    - name: cmake msys
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "export PATH=\"/c/msys64/usr/bin:$PATH:`CYGPATH -u -p \"%PATH%\"`\" && cd \"${{ github.workspace }}\" && export INSTALL_PREFIX=\"%INSTALL_PREFIX%\" && export CUTTER_PATH=\"%CUTTER_PATH%\" && ./scripts/msys_build.sh"
