name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  INSTALL_PREFIX: ${{ github.workspace }}/radare2-prefix
  CUTTER_PATH: ${{ github.workspace }}/cutter

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7.x]   
        # Prevent one job from pausing the rest
        fail-fast: [false]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        persist-credentials: false
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: py dependencies
      run: |
        pip install meson ninja
    - name: repo dependencies
      shell: bash
      run: |
        git clone --depth 1 https://github.com/radareorg/radare2
        git clone --depth 1 https://github.com/radareorg/cutter
    - name: Radare2 build
      shell: cmd
      run: |
        cd radare2 
        mkdir build
        cd build
        meson --prefix="${{ env.INSTALL_PREFIX }}" ..
        ninja
        ninja install
        cd ../..
    - name: msys dependencies
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "pacman -Sy --noconfirm bison flex"
    - name: cmake msys
      shell: cmd
      run: |
        C:\msys64\usr\bin\bash -lc "export PATH=\"/c/msys64/usr/bin:$PATH:`CYGPATH -u -p \"%PATH%\"`\" && cd \"${{ github.workspace }}\" && export INSTALL_PREFIX=\"${{ env.INSTALL_PREFIX }}\" && export CUTTER_PATH=\"${{ env.CUTTER_PATH }}\" && ./scripts/msys_build.sh"
